import 'package:flutter/material.dart';
import '../models/booking.dart';
import '../services/admin_api.dart';
import '../theme/app_theme.dart';
import 'clients_screen.dart';
import 'contracts_screen.dart';
import 'payments_screen.dart';

class DashboardScreen extends StatefulWidget { final AdminApi api; const DashboardScreen({super.key,required this.api}); @override State<DashboardScreen> createState()=>_DashboardScreenState(); }
class _DashboardScreenState extends State<DashboardScreen>{ late Future<List<Booking>> future; @override void initState(){super.initState();future=widget.api.getBookings();} void refresh()=>setState(()=>future=widget.api.getBookings());
@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Dashboard',style:TextStyle(fontWeight:FontWeight.w800)),actions:[IconButton(onPressed:refresh,icon:const Icon(Icons.refresh))]),drawer:_Drawer(api:widget.api),body:FutureBuilder<List<Booking>>(future:future,builder:(c,s){if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());if(s.hasError)return _Error(onRetry:refresh);final b=s.data??[];final pending=b.where((x)=>x.status=='pending').length;final revenue=b.fold<double>(0,(a,x)=>a+x.totalPrice);final clients=b.map((x)=>x.email).where((x)=>x.isNotEmpty).toSet().length;return RefreshIndicator(onRefresh:()async=>refresh(),child:ListView(padding:const EdgeInsets.all(18),children:[const Text('PURE & POWER',style:TextStyle(letterSpacing:2,fontWeight:FontWeight.w800,color:AppTheme.green)),const SizedBox(height:5),const Text('Vue générale',style:TextStyle(fontSize:30,fontWeight:FontWeight.w900,color:AppTheme.navy)),const SizedBox(height:22),GridView.count(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisCount:2,crossAxisSpacing:12,mainAxisSpacing:12,childAspectRatio:1.25,children:[_Stat('Réservations','${b.length}',Icons.calendar_month_outlined),_Stat('En attente','$pending',Icons.pending_actions_outlined),_Stat('Clients','$clients',Icons.people_outline),_Stat('CA estimé','${revenue.toStringAsFixed(0)} €',Icons.euro_outlined)]),const SizedBox(height:24),const Text('Dernières demandes',style:TextStyle(fontSize:20,fontWeight:FontWeight.w800)),const SizedBox(height:10),if(b.isEmpty)const _Empty() else ...b.take(5).map((x)=>_BookingTile(booking:x,onChanged:refresh,api:widget.api))]));});}
}
class _Stat extends StatelessWidget{final String title,value;final IconData icon;const _Stat(this.title,this.value,this.icon);@override Widget build(BuildContext c)=>Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Icon(icon,color:AppTheme.green,size:27),Text(value,style:const TextStyle(fontSize:25,fontWeight:FontWeight.w900,color:AppTheme.navy)),Text(title,style:const TextStyle(color:Colors.blueGrey))])));}
class _BookingTile extends StatelessWidget{final Booking booking;final VoidCallback onChanged;final AdminApi api;const _BookingTile({required this.booking,required this.onChanged,required this.api});@override Widget build(BuildContext c)=>Card(margin:const EdgeInsets.only(bottom:10),child:ListTile(contentPadding:const EdgeInsets.symmetric(horizontal:16,vertical:6),leading:CircleAvatar(backgroundColor:const Color(0xFFEAF2EC),child:Text(booking.clientName.isEmpty?'?':booking.clientName[0].toUpperCase(),style:const TextStyle(color:AppTheme.green,fontWeight:FontWeight.w800))),title:Text(booking.clientName.isEmpty?'Client':booking.clientName,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('${booking.service}\n${booking.date} • ${booking.time} • ${booking.totalPrice.toStringAsFixed(2)} €'),isThreeLine:true,trailing:_Status(booking.status),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>BookingDetailScreen(api:api,booking:booking,onChanged:onChanged))));}
class _Status extends StatelessWidget{final String status;const _Status(this.status);@override Widget build(BuildContext c){final pending=status=='pending';return Container(padding:const EdgeInsets.symmetric(horizontal:9,vertical:6),decoration:BoxDecoration(color:pending?const Color(0xFFFFF6E8):const Color(0xFFEAF2EC),borderRadius:BorderRadius.circular(20)),child:Text(pending?'En attente':status,style:TextStyle(fontSize:11,fontWeight:FontWeight.w800,color:pending?const Color(0xFF9A6A22):AppTheme.green)));}}
class _Empty extends StatelessWidget{const _Empty();@override Widget build(BuildContext c)=>const Card(child:Padding(padding:EdgeInsets.all(28),child:Column(children:[Icon(Icons.inbox_outlined,size:44,color:Colors.blueGrey),SizedBox(height:10),Text('Aucune demande',style:TextStyle(fontWeight:FontWeight.w800)),SizedBox(height:5),Text('Les nouvelles réservations apparaîtront ici.',textAlign:TextAlign.center,style:TextStyle(color:Colors.blueGrey))])));}
class _Error extends StatelessWidget{final VoidCallback onRetry;const _Error({required this.onRetry});@override Widget build(BuildContext c)=>Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.cloud_off_outlined,size:50),const SizedBox(height:12),const Text('Impossible de charger les données.',style:TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:12),FilledButton(onPressed:onRetry,child:const Text('Réessayer'))])));}
class _Drawer extends StatelessWidget{final AdminApi api;const _Drawer({required this.api});@override Widget build(BuildContext c)=>Drawer(child:ListView(padding:EdgeInsets.zero,children:[DrawerHeader(decoration:const BoxDecoration(color:AppTheme.navy),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const CircleAvatar(backgroundColor:AppTheme.green,child:Text('P&P',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w900))),const Spacer(),const Text('PURE & POWER',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w900,letterSpacing:1.5)),const Text('Administration mobile',style:TextStyle(color:Colors.white70))])),ListTile(leading:const Icon(Icons.dashboard_outlined),title:const Text('Dashboard'),onTap:()=>Navigator.pop(c)),ListTile(leading:const Icon(Icons.calendar_month_outlined),title:const Text('Réservations'),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>ReservationsScreen(api:api)))),ListTile(leading:const Icon(Icons.people_outline),title:const Text('Clients'),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>ClientsScreen(api:api)))),ListTile(leading:const Icon(Icons.description_outlined),title:const Text('Contrats'),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>ContractsScreen(api:api)))),ListTile(leading:const Icon(Icons.payments_outlined),title:const Text('Paiements'),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>PaymentsScreen(api:api)))),ListTile(leading:const Icon(Icons.settings_outlined),title:const Text('Paramètres'),onTap:()=>Navigator.pop(c))]));}
class ReservationsScreen extends StatefulWidget{final AdminApi api;const ReservationsScreen({super.key,required this.api});@override State<ReservationsScreen>createState()=>_ReservationsScreenState();}
class _ReservationsScreenState extends State<ReservationsScreen>{late Future<List<Booking>> f;@override void initState(){super.initState();f=widget.api.getBookings();}void reload()=>setState(()=>f=widget.api.getBookings());@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Réservations',style:TextStyle(fontWeight:FontWeight.w800)),actions:[IconButton(onPressed:reload,icon:const Icon(Icons.refresh))]),body:FutureBuilder<List<Booking>>(future:f,builder:(c,s){if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());if(s.hasError)return _Error(onRetry:reload);final list=s.data??[];return ListView(padding:const EdgeInsets.all(16),children:list.isEmpty?[const _Empty()]:list.map((b)=>_BookingTile(booking:b,onChanged:reload,api:widget.api)).toList());}));}}
class BookingDetailScreen extends StatelessWidget{final AdminApi api;final Booking booking;final VoidCallback onChanged;const BookingDetailScreen({super.key,required this.api,required this.booking,required this.onChanged});Future<void> decide(BuildContext c,String action)async{try{final r=await api.decide(booking.id,action);if(c.mounted){ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text(action=='approve'?(r['emailSent']==true?'Demande validée et email envoyé.':'Demande validée.'):'Demande refusée.')));onChanged();Navigator.pop(c);}}catch(e){if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text(e.toString())));}}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Détail de la demande')),body:ListView(padding:const EdgeInsets.all(18),children:[Text(booking.clientName,style:const TextStyle(fontSize:28,fontWeight:FontWeight.w900,color:AppTheme.navy)),const SizedBox(height:5),_Status(booking.status),const SizedBox(height:22),_Info('Prestation',booking.service),_Info('Date & heure','${booking.date} • ${booking.time}'),_Info('Montant','${booking.totalPrice.toStringAsFixed(2)} €'),_Info('Téléphone',booking.phone),_Info('Email',booking.email),_Info('Adresse',booking.address),if(booking.needs.isNotEmpty)_Info('Informations',booking.needs),if(booking.status=='pending')... [const SizedBox(height:18),Row(children:[Expanded(child:FilledButton.icon(onPressed:()=>decide(c,'approve'),icon:const Icon(Icons.check),label:const Text('Approuver'))),const SizedBox(width:10),Expanded(child:OutlinedButton.icon(onPressed:()=>decide(c,'reject'),icon:const Icon(Icons.close),label:const Text('Refuser')))])]));}
class _Info extends StatelessWidget{final String t,v;const _Info(this.t,this.v);@override Widget build(BuildContext c)=>Card(margin:const EdgeInsets.only(bottom:10),child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t.toUpperCase(),style:const TextStyle(fontSize:11,letterSpacing:1,fontWeight:FontWeight.w800,color:AppTheme.green)),const SizedBox(height:6),Text(v,style:const TextStyle(fontSize:16,fontWeight:FontWeight.w600))])));}
